export const DEFAULT_MOCK_DATA = {
  id: "NodeA",
  headerTitle: "Node-A",
  headerSubTitle: "Node-A-Subtitle",
  content: {
    valueA: "Node-A-Value-A",
    valueB: "Node-A-Value-B",
  },
  avatarUrl: "https://mui.com/static/images/avatar/1.jpg",
  showAvatar: true,
  layout: {
    headerBackgroundColor: "#123456",
    headerTitleColor: "#ffffff",
    headerSubtitleColor: "#cccccc",
  },
  children: [
    {
      id: "NodeAA",
      headerTitle: "Node-AA",
      headerSubTitle: "Node-AA-Subtitle",
      content: {
        valueA: "Node-AA-Value-A",
        valueB: "Node-AA-Value-B",
      },
      contentType: "person",
      avatarUrl: "https://mui.com/static/images/avatar/1.jpg",
      showAvatar: true,
      layout: {
        headerBackgroundColor: "#123456",
        headerTitleColor: "#ffffff",
        headerSubtitleColor: "#cccccc",
      },
      children: [
        {
          id: "NodeAAA",
          headerTitle: "Node-AAA",
          headerSubTitle: "Node-AAA-Subtitle",
          content: {
            valueA: "Node-AAA-Value-A",
            valueB: "Node-AAA-Value-B",
          },
          avatarUrl: "https://mui.com/static/images/avatar/1.jpg",
          showAvatar: true,
          layout: {
            headerBackgroundColor: "#123456",
            headerTitleColor: "#ffffff",
            headerSubtitleColor: "#cccccc",
          },
          children: [],
        },
        {
          id: "NodeAAB",
          headerTitle: "Node-AAB",
          headerSubTitle: "Node-AAB-Subtitle",
          content: {
            valueA: "Node-AAB-Value-A",
            valueB: "Node-AAB-Value-B",
          },
          avatarUrl: "https://mui.com/static/images/avatar/1.jpg",
          showAvatar: true,
          layout: {
            headerBackgroundColor: "#123456",
            headerTitleColor: "#ffffff",
            headerSubtitleColor: "#cccccc",
          },
          children: [
            {
              id: "NodeAABA",
              headerTitle: "Node-AABA",
              headerSubTitle: "Node-AABA-Subtitle",
              content: {
                valueA: "Node-AABA-Value-A",
                valueB: "Node-AABA-Value-B",
              },
              avatarUrl: "https://mui.com/static/images/avatar/1.jpg",
              showAvatar: true,
              layout: {
                headerBackgroundColor: "#123456",
                headerTitleColor: "#ffffff",
                headerSubtitleColor: "#cccccc",
              },
              children: [],
            },
            {
              id: "NodeAABB",
              headerTitle: "Node-AABB",
              headerSubTitle: "Node-AABB-Subtitle",
              content: {
                valueA: "Node-AABB-Value-A",
                valueB: "Node-AABB-Value-B",
              },
              avatarUrl: "https://mui.com/static/images/avatar/1.jpg",
              showAvatar: true,
              layout: {
                headerBackgroundColor: "#123456",
                headerTitleColor: "#ffffff",
                headerSubtitleColor: "#cccccc",
              },
              children: [],
            },
            {
              id: "NodeAABC",
              headerTitle: "Node-AABC",
              headerSubTitle: "Node-AABC-Subtitle",
              content: {
                valueA: "Node-AABC-Value-A",
                valueB: "Node-AABC-Value-B",
              },
              avatarUrl: "https://mui.com/static/images/avatar/1.jpg",
              showAvatar: true,
              layout: {
                headerBackgroundColor: "#123456",
                headerTitleColor: "#ffffff",
                headerSubtitleColor: "#cccccc",
              },
              children: [],
            },
          ],
        },
        {
          id: "NodeAAC",
          headerTitle: "Node-AAC",
          headerSubTitle: "Node-AAC-Subtitle",
          content: {
            valueA: "Node-AAC-Value-A",
            valueB: "Node-AAC-Value-B",
          },
          avatarUrl: "https://mui.com/static/images/avatar/1.jpg",
          showAvatar: true,
          layout: {
            headerBackgroundColor: "#123456",
            headerTitleColor: "#ffffff",
            headerSubtitleColor: "#cccccc",
          },
          children: [],
        },
        {
          id: "NodeAAD",
          headerTitle: "Node-AAD",
          headerSubTitle: "Node-AAD-Subtitle",
          content: {
            valueA: "Node-AAD-Value-A",
            valueB: "Node-AAD-Value-B",
          },
          avatarUrl: "https://mui.com/static/images/avatar/1.jpg",
          showAvatar: true,
          layout: {
            headerBackgroundColor: "#123456",
            headerTitleColor: "#ffffff",
            headerSubtitleColor: "#cccccc",
          },
          children: [
            {
              id: "NodeAADA",
              headerTitle: "Node-AADA",
              headerSubTitle: "Node-AADA-Subtitle",
              content: {
                valueA: "Node-AADA-Value-A",
                valueB: "Node-AADA-Value-B",
              },
              avatarUrl: "https://mui.com/static/images/avatar/1.jpg",
              showAvatar: true,
              layout: {
                headerBackgroundColor: "#123456",
                headerTitleColor: "#ffffff",
                headerSubtitleColor: "#cccccc",
              },
              children: [],
            },
            {
              id: "NodeAADB",
              headerTitle: "Node-AADB",
              headerSubTitle: "Node-AADB-Subtitle",
              content: {
                valueA: "Node-AADB-Value-A",
                valueB: "Node-AADB-Value-B",
              },
              avatarUrl: "https://mui.com/static/images/avatar/1.jpg",
              showAvatar: true,
              layout: {
                headerBackgroundColor: "#123456",
                headerTitleColor: "#ffffff",
                headerSubtitleColor: "#cccccc",
              },
              children: [],
            },
          ],
        },
      ],
    },
    {
      id: "NodeAB",
      headerTitle: "Node-AB",
      headerSubTitle: "Node-AB-Subtitle",
      content: {
        valueA: "Node-AB-Value-A",
        valueB: "Node-AB-Value-B",
      },
      avatarUrl: "https://mui.com/static/images/avatar/1.jpg",
      showAvatar: true,
      layout: {
        headerBackgroundColor: "#123456",
        headerTitleColor: "#ffffff",
        headerSubtitleColor: "#cccccc",
      },
      children: [
        {
          id: "NodeABA",
          headerTitle: "Node-ABA",
          headerSubTitle: "Node-ABA-Subtitle",
          content: {
            valueA: "Node-ABA-Value-A",
            valueB: "Node-ABA-Value-B",
          },
          avatarUrl: "https://mui.com/static/images/avatar/1.jpg",
          showAvatar: true,
          layout: {
            headerBackgroundColor: "#123456",
            headerTitleColor: "#ffffff",
            headerSubtitleColor: "#cccccc",
          },
          children: [],
        },
        {
          id: "NodeABB",
          headerTitle: "Node-ABB",
          headerSubTitle: "Node-ABB-Subtitle",
          content: {
            valueA: "Node-ABB-Value-A",
            valueB: "Node-ABB-Value-B",
          },
          avatarUrl: "https://mui.com/static/images/avatar/1.jpg",
          showAvatar: true,
          layout: {
            headerBackgroundColor: "#123456",
            headerTitleColor: "#ffffff",
            headerSubtitleColor: "#cccccc",
          },
          children: [],
        },
      ],
    },
    {
      id: "NodeAC",
      headerTitle: "Node-AC",
      headerSubTitle: "Node-AC-Subtitle",
      content: {
        valueA: "Node-AC-Value-A",
        valueB: "Node-AC-Value-B",
      },
      avatarUrl: "https://mui.com/static/images/avatar/1.jpg",
      showAvatar: true,
      layout: {
        headerBackgroundColor: "#123456",
        headerTitleColor: "#ffffff",
        headerSubtitleColor: "#cccccc",
      },
      children: [
        {
          id: "NodeACA",
          headerTitle: "Node-ACA",
          headerSubTitle: "Node-ACA-Subtitle",
          content: {
            valueA: "Node-ACA-Value-A",
            valueB: "Node-ACA-Value-B",
          },
          avatarUrl: "https://mui.com/static/images/avatar/1.jpg",
          showAvatar: true,
          layout: {
            headerBackgroundColor: "#123456",
            headerTitleColor: "#ffffff",
            headerSubtitleColor: "#cccccc",
          },
          children: [],
        },
      ],
    },
    {
      id: "NodeAD",
      headerTitle: "Node-AD",
      headerSubTitle: "Node-AD-Subtitle",
      content: {
        valueA: "Node-AD-Value-A",
        valueB: "Node-AD-Value-B",
      },
      avatarUrl: "https://mui.com/static/images/avatar/1.jpg",
      showAvatar: true,
      layout: {
        headerBackgroundColor: "#123456",
        headerTitleColor: "#ffffff",
        headerSubtitleColor: "#cccccc",
      },
      children: [
        {
          id: "NodeADA",
          headerTitle: "Node-ADA",
          headerSubTitle: "Node-ADA-Subtitle",
          content: {
            valueA: "Node-ADA-Value-A",
            valueB: "Node-ADA-Value-B",
          },
          avatarUrl: "https://mui.com/static/images/avatar/1.jpg",
          showAvatar: true,
          layout: {
            headerBackgroundColor: "#123456",
            headerTitleColor: "#ffffff",
            headerSubtitleColor: "#cccccc",
          },
          children: [],
        },
        {
          id: "NodeADB",
          headerTitle: "Node-ADB",
          headerSubTitle: "Node-ADB-Subtitle",
          content: {
            valueA: "Node-ADB-Value-A",
            valueB: "Node-ADB-Value-B",
          },
          avatarUrl: "https://mui.com/static/images/avatar/1.jpg",
          showAvatar: true,
          layout: {
            headerBackgroundColor: "#123456",
            headerTitleColor: "#ffffff",
            headerSubtitleColor: "#cccccc",
          },
          children: [],
        },
        {
          id: "NodeADC",
          headerTitle: "Node-ADC",
          headerSubTitle: "Node-ADC-Subtitle",
          content: {
            valueA: "Node-ADC-Value-A",
            valueB: "Node-ADC-Value-B",
          },
          avatarUrl: "https://mui.com/static/images/avatar/1.jpg",
          showAvatar: true,
          layout: {
            headerBackgroundColor: "#123456",
            headerTitleColor: "#ffffff",
            headerSubtitleColor: "#cccccc",
          },
          children: [],
        },
        {
          id: "NodeADD",
          headerTitle: "Node-ADD",
          headerSubTitle: "Node-ADD-Subtitle",
          content: {
            valueA: "Node-ADD-Value-A",
            valueB: "Node-ADD-Value-B",
          },
          avatarUrl: "https://mui.com/static/images/avatar/1.jpg",
          showAvatar: true,
          layout: {
            headerBackgroundColor: "#123456",
            headerTitleColor: "#ffffff",
            headerSubtitleColor: "#cccccc",
          },
          children: [],
        },
        {
          id: "NodeADE",
          headerTitle: "Node-ADE",
          headerSubTitle: "Node-ADE-Subtitle",
          content: {
            valueA: "Node-ADE-Value-A",
            valueB: "Node-ADE-Value-B",
          },
          avatarUrl: "https://mui.com/static/images/avatar/1.jpg",
          showAvatar: true,
          layout: {
            headerBackgroundColor: "#123456",
            headerTitleColor: "#ffffff",
            headerSubtitleColor: "#cccccc",
          },
          children: [],
        },
      ],
    },
    {
      id: "NodeAE",
      headerTitle: "Node-AE",
      headerSubTitle: "Node-AE-Subtitle",
      content: {
        valueA: "Node-AE-Value-A",
        valueB: "Node-AE-Value-B",
      },
      avatarUrl: "https://mui.com/static/images/avatar/1.jpg",
      showAvatar: true,
      layout: {
        headerBackgroundColor: "#123456",
        headerTitleColor: "#ffffff",
        headerSubtitleColor: "#cccccc",
      },
      children: [],
    },
  ],
};
